"""entrenamiento

Revision ID: 11841485d0b2
Revises: 3c0486273193
Create Date: 2026-08-10 10:39:08.027383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11841485d0b2'
down_revision: Union[str, Sequence[str], None] = '3c0486273193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_nutricionales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entrenador_id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('borrador_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenadores.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutinas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entrenador_id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('borrador_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenadores.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ejercicios_rutina',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rutina_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(), nullable=False),
    sa.Column('descanso_segundos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cumplimiento_rutina',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ejercicio_id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios_rutina.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cumplimiento_rutina')
    op.drop_table('ejercicios_rutina')
    op.drop_table('rutinas')
    op.drop_table('planes_nutricionales')
    # ### end Alembic commands ###
