"""pagos

Revision ID: 266853c6c8d4
Revises: 11841485d0b2
Create Date: 2026-08-10 11:52:18.430407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266853c6c8d4'
down_revision: Union[str, Sequence[str], None] = '11841485d0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remesas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('membresia_id', sa.UUID(), nullable=True),
    sa.Column('concepto', sa.String(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pago_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('anulada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('remesa_pagos',
    sa.Column('remesa_id', sa.UUID(), nullable=False),
    sa.Column('pago_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['remesa_id'], ['remesas.id'], ),
    sa.PrimaryKeyConstraint('remesa_id', 'pago_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remesa_pagos')
    op.drop_table('facturas')
    op.drop_table('pagos')
    op.drop_table('remesas')
    # ### end Alembic commands ###
