"""asistente_ia

Revision ID: 2abd213f134d
Revises: deb0740ca027
Create Date: 2026-08-13 11:13:36.237921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2abd213f134d'
down_revision: Union[str, Sequence[str], None] = 'deb0740ca027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borradores_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('entrenador_revisor_id', sa.UUID(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrenador_revisor_id'], ['entrenadores.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversaciones_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones_ia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # rutinas.borrador_id y planes_nutricionales.borrador_id (módulo 007) se
    # crearon como UUID suelto, sin FK, porque borradores_ia no existía
    # todavía (ver comentario en entrenamiento/models.py). Ahora que la
    # tabla existe, se añade la FK real pendiente.
    op.create_foreign_key(
        'rutinas_borrador_id_fkey', 'rutinas', 'borradores_ia', ['borrador_id'], ['id']
    )
    op.create_foreign_key(
        'planes_nutricionales_borrador_id_fkey', 'planes_nutricionales', 'borradores_ia', ['borrador_id'], ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('planes_nutricionales_borrador_id_fkey', 'planes_nutricionales', type_='foreignkey')
    op.drop_constraint('rutinas_borrador_id_fkey', 'rutinas', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes_ia')
    op.drop_table('conversaciones_ia')
    op.drop_table('borradores_ia')
    # ### end Alembic commands ###
