"""entrenadores_completo

Revision ID: 3c0486273193
Revises: 7e72da7f8741
Create Date: 2026-08-10 10:22:09.092845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c0486273193'
down_revision: Union[str, Sequence[str], None] = '7e72da7f8741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socios_asignados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entrenador_id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenadores.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entrenadores', sa.Column('sede_id', sa.UUID(), nullable=False))
    op.add_column('entrenadores', sa.Column('especialidades', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('entrenadores', sa.Column('horario_disponible', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'entrenadores', 'sedes', ['sede_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entrenadores', type_='foreignkey')
    op.drop_column('entrenadores', 'horario_disponible')
    op.drop_column('entrenadores', 'especialidades')
    op.drop_column('entrenadores', 'sede_id')
    op.drop_table('socios_asignados')
    # ### end Alembic commands ###
