"""membresias

Revision ID: 550f784f5ad2
Revises: bfccca424591
Create Date: 2026-08-09 12:44:45.553732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550f784f5ad2'
down_revision: Union[str, Sequence[str], None] = 'bfccca424591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_membresia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duracion', sa.String(), nullable=False),
    sa.Column('alcance', sa.String(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=True),
    sa.Column('preaviso_cancelacion_dias', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membresias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_proxima_renovacion', sa.Date(), nullable=False),
    sa.Column('renovacion_automatica', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_cancelacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_membresia.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('congelaciones_membresia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('membresia_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('origen', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_estados_membresia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('membresia_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(), nullable=True),
    sa.Column('estado_nuevo', sa.String(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_estados_membresia')
    op.drop_table('congelaciones_membresia')
    op.drop_table('membresias')
    op.drop_table('planes_membresia')
    # ### end Alembic commands ###
