"""notificaciones

Revision ID: 62b1ea8f4325
Revises: 71aa7379e7ce
Create Date: 2026-08-12 12:26:46.196641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b1ea8f4325'
down_revision: Union[str, Sequence[str], None] = '71aa7379e7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('cuerpo', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferencias_notificacion',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('marketing_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferencias_notificacion')
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
