"""historial_acciones_pago

Revision ID: 71aa7379e7ce
Revises: 8a2cdb12e0c1
Create Date: 2026-08-11 19:25:11.796178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71aa7379e7ce'
down_revision: Union[str, Sequence[str], None] = '8a2cdb12e0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_acciones_pago',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidad_tipo', sa.String(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_acciones_pago')
    # ### end Alembic commands ###
