"""accesos

Revision ID: 7e1b8b7d131e
Revises: 266853c6c8d4
Create Date: 2026-08-10 12:20:18.032301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1b8b7d131e'
down_revision: Union[str, Sequence[str], None] = '266853c6c8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesos')
    # ### end Alembic commands ###
