"""crm leads

Revision ID: 8a2cdb12e0c1
Revises: 7e1b8b7d131e
Create Date: 2026-08-10 17:57:21.619366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2cdb12e0c1'
down_revision: Union[str, Sequence[str], None] = '7e1b8b7d131e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('sede_interes_id', sa.UUID(), nullable=False),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('comercial_id', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comercial_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sede_interes_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interacciones_lead',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interacciones_lead')
    op.drop_table('leads')
    # ### end Alembic commands ###
