"""socios

Revision ID: bfccca424591
Revises: 3c005e70a49e
Create Date: 2026-08-09 12:18:47.440226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfccca424591'
down_revision: Union[str, Sequence[str], None] = '3c005e70a49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('contacto_emergencia_nombre', sa.String(), nullable=False),
    sa.Column('contacto_emergencia_telefono', sa.String(), nullable=False),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('documentos_socio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('archivo_url', sa.String(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_sedes_socio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_socio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas_socio')
    op.drop_table('historial_sedes_socio')
    op.drop_table('documentos_socio')
    op.drop_table('socios')
    # ### end Alembic commands ###
