"""configuracion

Revision ID: deb0740ca027
Revises: 62b1ea8f4325
Create Date: 2026-08-12 13:16:10.286566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb0740ca027'
down_revision: Union[str, Sequence[str], None] = '62b1ea8f4325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_global',
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('historial_configuracion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor_anterior', sa.String(), nullable=False),
    sa.Column('valor_nuevo', sa.String(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['clave'], ['configuracion_global.clave'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Parámetros globales de spec.md FR-1 (moneda, zona horaria, textos
    # legales): se siembran aquí porque el contrato de plan.md solo expone
    # PUT /configuracion/{clave} (editar), no un POST para crear claves nuevas.
    configuracion_global = sa.table(
        'configuracion_global',
        sa.column('clave', sa.String),
        sa.column('valor', sa.String),
        sa.column('tipo', sa.String),
    )
    op.bulk_insert(
        configuracion_global,
        [
            {'clave': 'moneda', 'valor': 'EUR', 'tipo': 'texto'},
            {'clave': 'zona_horaria', 'valor': 'Europe/Madrid', 'tipo': 'texto'},
            {'clave': 'texto_politica_privacidad', 'valor': '', 'tipo': 'texto'},
            {'clave': 'texto_condiciones', 'valor': '', 'tipo': 'texto'},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_configuracion')
    op.drop_table('configuracion_global')
    # ### end Alembic commands ###
